<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0</AssemblyVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.0.10" />
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
    <PackageReference Include="Terminal.Gui" Version="1.19.0" />
    <EmbeddedResource Include="Datas\Languages.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="EasyLog\EasyLog.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="EasySave.Tests/**" />
    <Compile Remove="EasyLog/**" />
  </ItemGroup>

</Project>